// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYywteNmXlJFfFOpCDL1QkcnxR_2iSSXI',
    appId: '1:980147663720:web:a9a12ead9a78ca1fd65cdd',
    messagingSenderId: '980147663720',
    projectId: 'firestore-a550e',
    authDomain: 'firestore-a550e.firebaseapp.com',
    storageBucket: 'firestore-a550e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7AEDj3w4H_J8fl1EmUqm22wia7i4m2kQ',
    appId: '1:980147663720:android:7e408a34775e43dad65cdd',
    messagingSenderId: '980147663720',
    projectId: 'firestore-a550e',
    storageBucket: 'firestore-a550e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkK-srFe3hE29kUfydc2YDFnPi8QjJZIE',
    appId: '1:980147663720:ios:46481bb217d9b5edd65cdd',
    messagingSenderId: '980147663720',
    projectId: 'firestore-a550e',
    storageBucket: 'firestore-a550e.firebasestorage.app',
    iosBundleId: 'com.codexia.firestore',
  );
}
